const membersData = [
	{
		name: "Vlad Meșa",
		class: 2027,
		classIndex: "",
		birth: new Date(2007, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Vlad.jpg",
		thumbnailImage: "static/photo/Vlad.jpg",
		passions: "Inginerie aerospațială, 3D design, 3D printing",
		roles: [1],
		description: "Am fost pasionat de inginerie și inginerie aerospațială în ultimii 6 ani. Am folosit software CAD profesional și imprimante 3D pentru a realiza nenumărate proiecte de robotică, precum și modele de aeronave. Recent, m-am alăturat FTC cu scopul de a lucra în echipă și de a-mi aplica cunoștințele și expertiza în robotica competitivă.",
	},
	{
		name: "Robert Silea",
		class: 2027,
		classIndex: "A",
		birth: new Date(2007, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Robi.JPG",
		thumbnailImage: "static/photo/Robi.JPG",
		passions: "Motorsport, video-editing, mecanica",
		roles: [1],
		description: "Bunăă, mă numesc Robi, am 17 ani și sunt pentru al doilea an la RoboAS. Provin de la țară, de unde mi-a venit pasiunea asta pentru a crea lucruri, din moment ce am reparat de atâtea ori tractoare cu tatăl meu :). Mă consider foarte sociabil, o persoană de la care poți să înveți multe lucruri și îmi place să lucrez alături de această echipă.",
	},
	{
		name: "David Răileanu",
		class: 2028,
		classIndex: "B",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/David.jpg",
		thumbnailImage: "static/photo/David.jpg",
		passions: "cout<<“nu stiu ce sa scriu aici”;",
		roles: [1],
		description: "Neatza! Știi omul ăla care face mereu echipa să râdă chiar și în cele mai nasoale momente? Nu, nu sunt eu! Eu sunt David! Glumesc, glumesc! Îmi place să cred că pot să readuc echipa la viață oricât de moartă ar fi. Sunt în clasa a X-a B și mă ocup cu proiectarea 3D (dar și șurubareala la mecatronica) în cadrul echipei RoboAs.Sunt mereu la datorie să dau o mână de ajutor coechiperilor mei și să vin cu idei. Îmi place cam tot ce e legat de tehnologie(Arduino/lego), mai ales dacă îmi pot face vizibilă contribuția. În general timpul liber mi-l umplu cu o grămadă de activități artistice :cor, fanfară dar și NSS, ACSL și diferite cercuri de mate. PS de o bună perioadă tot încerc să învăț sa gătesc, dar nu-mi iese, cam atât :)",
	},
	{
		name: "Anne Stavarache",
		class: 2029,
		classIndex: "A",
		birth: new Date(2009, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Anne.JPG",
		thumbnailImage: "static/photo/Anne.JPG",
		passions: "Developing în Minecraft, muzica electronică, pictat",
		roles: [1],
		description: "Hei, buna! Eu sunt Ana și rolul meu în echipă este acela de a ajuta la montajul subansamblelor celui mai fiabil robot împreună cu prietenii mei. Sunt o fire prietenoasă, curioasă si ambițioasă. Tot ce îmi doresc este să ne clasăm pe un loc onorabil la fiecare concurs.",
	},
	{
		name: "Daria Lazăr",
		class: 2027,
		classIndex: "A",
		birth: new Date(2007, 1, 15, 0, 0) * 1,
		descriptionImage: "static/photo/Daria.jpg",
		thumbnailImage: "static/photo/Daria.jpg",
		passions: "",
		roles: [0],
		description: "",
	},
	{
		name: "Teodora Stoica",
		class: 2028,
		classIndex: "A",
		birth: new Date(2008, 12, 4, 0, 0) * 1,
		descriptionImage: "static/photo/Tea.jpg",
		thumbnailImage: "static/photo/Tea.jpg",
		passions: "programarea, sportul",
		roles: [0],
		description: "heey!! Sunt Tea, sunt în clasa X A și sunt în primul an în cadrul echipei, unde o să mă ocup de programare. Când nu scriu cod, fac mult sport, ca snowboardul sau tenisul, sau ascult muzică, iar în rest îmi place să încerc lucruri noi. That's all :)",
	},
	{
		name: "Alexandru Colojoară",
		class: 2029,
		classIndex: "A",
		birth: new Date(2009, 1, 15, 0, 0) * 1,
		descriptionImage: "static/photo/Alex.jpg",
		thumbnailImage: "static/photo/Alex.jpg",
		passions: "Arte Marțiale, Programare, Airsoft",
		roles: [0],
		description: "Salut! Sunt Colojoară Alexandru, am 16 ani și sunt programator în echipa RoboAS. Îmi place să fiu mereu activ: fac arte marțiale, joc airsoft, înot, mă antrenez în tot felul de sporturi și, bineînțeles, sunt pasionat de programare și informatică. Când am timp liber, mă relaxez cu jocuri video sau mă provoc să învăț lucruri noi. Mă consider un tip amuzant, sociabil și determinat. Îmi place să îmi asum responsabilități și nu renunț ușor când îmi propun ceva — sunt genul de persoană care merge până la capăt. Visul meu e simplu: să am o viață frumoasă și să mă bucur de fiecare pas făcut spre ceea ce îmi doresc.",
	},
	{
		name: "Alexa Șerban",
		class: 2026,
		classIndex: "E",
		birth: new Date(2006, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Alexa.JPG",
		thumbnailImage: "static/photo/Alexa.JPG",
		passions: "Managementul, relațiile inter-umane, muzica",
		roles: [2],
		description: "Sunt Alexa — mă entuziasmez ușor, sar de la o idee la alta și cred că cele mai faine lucruri ies când pui suflet, nu când totul e perfect. Îmi place să fiu în mijlocul oamenilor, să am o energie bună și să adun povești. Tocmai de aceea încerc mereu să văd partea pozitivă în orice (sau oricine). :)",
	},
	{
		name: "Amalia Călugăru",
		class: 2028,
		classIndex: "D",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Ami.jpg",
		thumbnailImage: "static/photo/Ami.jpg",
		passions: "fotografia, muzica și animalele",
		roles: [2],
		description: "Hi! Eu sunt Ami, îmi plac animalele foarte mult și îmi place să surprind momente faine prin obiectivul camerei mele. Experiențele FTC au fost unele dintre cele mai tari din viața mea și mă bucur foarte mult că fac parte din echipa RoboAS <3",
	},
	{
		name: "Rareș Alexandru",
		class: 2029,
		classIndex: "A",
		birth: new Date(2009, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Rares.jpg",
		thumbnailImage: "static/photo/Rares.jpg",
		passions: "Calisthenics, Electronica, Muzica",
		roles: [2],
		description: "Sunt pasionat de calisthenics, un mod de a-mi îmbunătăți forța și flexibilitatea prin exerciții proprii corpului. În paralel, mă fascinează domeniul electronicii, unde explorez circuite și tehnologii inovative. De asemenea, îmi place să modelez 3D, creând designuri și obiecte virtuale care reflectă imaginația mea creativă.",
	},
	{
		name: "Rebecca Cojocaru",
		class: 2028,
		classIndex: "F",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Rebe.JPG",
		thumbnailImage: "static/photo/Rebe.JPG",
		passions: "Călătorit, Graphic design",
		roles: [2],
		description: "Mă numesc Rebecca, am 17 ani și sunt eleva in clasa a X-a. Mǎ consider o persoană empatică, creativă, dar și sociabilǎ. Îmi place să lucrez în echipă și sǎ-mi împǎrtǎșesc ideile cu ceilalți. În plus, sunt o fire devotată, așadar mă implic cu responsabilitate în tot ceea ce fac, cu scopul de a atinge cele mai bune rezultate, atât pentru mine, cât si pentru cei din jur.",
	}
]
